# Project Objective

The objective of this task is to prepare the e-commerce dataset for Exploratory data analysis by handling missing values, removing duplicates, and formatting the data correctly.

## Import Libraries

In [1]:
import pandas as pd

## Loading Dataset

In [2]:
orders_df = pd.read_excel("C:/Users/Rasheedat/Downloads/Online_Stores_Orders.xlsx")

## Inspecting dataset structure

In [3]:
orders_df.head(2)

,OrderID,Date,CustomerID,Product,Quantity,UnitPrice,ShippingAddress,PaymentMethod,OrderStatus,TrackingNumber,ItemsInCart,CouponCode,ReferralSource,TotalPrice
0,ORD200000,2023-01-04,C72649,Monitor,5,570.62,928 Main St,Debit Card,Shipped,TRK37947903,7,SAVE10,Instagram,2853.1
1,ORD200001,2024-08-23,C75739,Phone,2,151.35,823 Main St,Online,Shipped,TRK91186779,3,SAVE10,Referral,302.7

In [4]:
orders_df.tail(2)

,OrderID,Date,CustomerID,Product,Quantity,UnitPrice,ShippingAddress,PaymentMethod,OrderStatus,TrackingNumber,ItemsInCart,CouponCode,ReferralSource,TotalPrice
1198,ORD201198,2024-08-22,C64753,Chair,4,262.52,509 Main St,Debit Card,Cancelled,TRK71683331,4,WINTER15,Instagram,1050.08
1199,ORD201199,2023-06-11,C57502,Tablet,4,560.58,201 Main St,Gift Card,Returned,TRK51116746,6,SAVE10,Referral,2242.32

In [5]:
orders_df.shape

(1200, 14)

In [6]:
orders_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1200 entries, 0 to 1199
Data columns (total 14 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   OrderID          1200 non-null   object
 1   Date             1200 non-null   datetime64[ns]
 2   CustomerID       1200 non-null   object
 3   Product          1200 non-null   object
 4   Quantity         1200 non-null   int64
 5   UnitPrice        1200 non-null   float64
 6   ShippingAddress  1200 non-null   object
 7   PaymentMethod    1200 non-null   object
 8   OrderStatus      1200 non-null   object
 9   TrackingNumber   1200 non-null   object
 10  ItemsInCart      1200 non-null   int64
 11  CouponCode       891 non-null    object
 12  ReferralSource   1200 non-null   object
 13  TotalPrice       1200 non-null   float64
dtypes: datetime64[ns](1), float64(2), int64(2), object(9)
memory usage: 131.4+ KB

##### Renamed column names to snake_case format for improved readability and consistency.

In [7]:
orders_df.columns

Index(['OrderID', 'Date', 'CustomerID', 'Product', 'Quantity', 'UnitPrice',
       'ShippingAddress', 'PaymentMethod', 'OrderStatus', 'TrackingNumber',
       'ItemsInCart', 'CouponCode', 'ReferralSource', 'TotalPrice'],
      dtype='object')

In [8]:
orders_df.columns = orders_df.columns.str.lower()

In [9]:
orders_df.columns

Index(['orderid', 'date', 'customerid', 'product', 'quantity', 'unitprice',
       'shippingaddress', 'paymentmethod', 'orderstatus', 'trackingnumber',
       'itemsincart', 'couponcode', 'referralsource', 'totalprice'],
      dtype='object')

In [10]:
orders_df.columns = [
    'order_id',
    'date',
    'customer_id',
    'product',
    'quantity',
    'unit_price',
    'shipping_address',
    'payment_method',
    'order_status',
    'tracking_number',
    'items_in_cart',
    'coupon_code',
    'referral_source',
    'total_price'
]

In [11]:
orders_df.columns

Index(['order_id', 'date', 'customer_id', 'product', 'quantity', 'unit_price',
       'shipping_address', 'payment_method', 'order_status', 'tracking_number',
       'items_in_cart', 'coupon_code', 'referral_source', 'total_price'],
      dtype='object')

## Unique Value Analysis

This section examines the number of unique values present in each column to better understand the diversity and variability of the dataset features.

In [12]:
unique_values = pd.DataFrame({
    'Column': orders_df.columns,
    'Unique Values': orders_df.nunique().values
})

unique_values

              Column  Unique Values
0           order_id           1200
1               date            671
2        customer_id           1189
3            product              7
4           quantity              5
5         unit_price           1193
6   shipping_address            655
7     payment_method              5
8       order_status              5
9    tracking_number           1200
10     items_in_cart             10
11       coupon_code              3
12   referral_source              5
13       total_price           1195

## Checking and handling missing values

In [13]:
orders_df.isnull().sum()

order_id              0
date                  0
customer_id           0
product               0
quantity              0
unit_price            0
shipping_address      0
payment_method        0
order_status          0
tracking_number       0
items_in_cart         0
coupon_code         309
referral_source       0
total_price           0
dtype: int64

In [14]:
orders_df.dropna(subset=['coupon_code'], inplace=True)

In [15]:
orders_df['coupon_code'].isnull().sum()

np.int64(0)

## Check for duplicates

##### Checked for duplicate records to ensure data consistency.

In [16]:
orders_df.duplicated().sum()

np.int64(0)

## Previewing cleaned dataset

In [17]:
orders_df.head(3)

,order_id,date,customer_id,product,quantity,unit_price,shipping_address,payment_method,order_status,tracking_number,items_in_cart,coupon_code,referral_source,total_price
0,ORD200000,2023-01-04,C72649,Monitor,5,570.62,928 Main St,Debit Card,Shipped,TRK37947903,7,SAVE10,Instagram,2853.1
1,ORD200001,2024-08-23,C75739,Phone,2,151.35,823 Main St,Online,Shipped,TRK91186779,3,SAVE10,Referral,302.7
2,ORD200002,2024-02-27,C81728,Tablet,5,550.68,512 Main St,Credit Card,Cancelled,TRK42903982,8,FREESHIP,Email,2753.4

In [18]:
orders_df.shape

(891, 14)

In [19]:
orders_df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 891 entries, 0 to 1199
Data columns (total 14 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   order_id          891 non-null    object
 1   date              891 non-null    datetime64[ns]
 2   customer_id       891 non-null    object
 3   product           891 non-null    object
 4   quantity          891 non-null    int64
 5   unit_price        891 non-null    float64
 6   shipping_address  891 non-null    object
 7   payment_method    891 non-null    object
 8   order_status      891 non-null    object
 9   tracking_number   891 non-null    object
 10  items_in_cart     891 non-null    int64
 11  coupon_code       891 non-null    object
 12  referral_source   891 non-null    object
 13  total_price       891 non-null    float64
dtypes: datetime64[ns](1), float64(2), int64(2), object(9)
memory usage: 104.4+ KB

In [20]:
orders_df.isnull().sum()

order_id            0
date                0
customer_id         0
product             0
quantity            0
unit_price          0
shipping_address    0
payment_method      0
order_status        0
tracking_number     0
items_in_cart       0
coupon_code         0
referral_source     0
total_price         0
dtype: int64

## Saving cleaned dataset

In [21]:
orders_df.to_csv("cleaned_orders.csv", index=False)